### PR TITLE
Upgrade playwright to v1.33.0

### PR DESCRIPTION
**Pull request by tianfeng92**

### CODE REVIEW

**Comment by tianfeng92** [comment]
hmm.. The generating junit part is not function well. Let me convert it to draft and check more details

**Comment by tianfeng92** [comment]
Fixed. It should work now.

**Comment by alexplischke** [comment]
I noticed that we get this printout in the jobs when installing deps:
```
npm notice 
npm notice New patch version of npm available! 9.6.0 -> 9.6.5
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.5>
npm notice Run `npm install -g npm@9.6.5` to update!
npm notice 
```

Would be good to silence, since it's irrelevant to the user (nothing they can do about) 🙏

**Review by FriggaHel — APPROVED** [review]

**Review by alexplischke — COMMENTED** [review]
Still no silencing? Because if NPM rolls out an update, this runner will start spewing a warning again. Simply using the most updated version _at this time_ is not going to help with future updates.

**Comment by tianfeng92** [comment]
Tested with https://github.com/saucelabs/sauce-runner-utils/pull/53/. npm update notification got muted.

https://app.saucelabs.com/tests/85cddbcc9b8a4606b2ad78529b6211a9

**Review by alexplischke — APPROVED** [review]

**Pull request merged**
